# Generated by Django 3.0.5 on 2021-02-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XmlData',
        ),
    ]
