# Generated by Django 3.0.5 on 2021-02-13 13:14

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XmlData',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('xml_attributes', djongo.models.fields.JSONField()),
            ],
        ),
    ]
